### ISSUE TITLE
ram is yanked

### ISSUE THREAD

**Issue by tobiasvl** [conradkleinespel/duck#33]
`ram`'s README says you can add it as a dependency to `Cargo.toml` and also links to `docs.rs/ram`, but the crate is yanked from `crates.io` and so neither works.

**Comment by conradkleinespel** [comment]
Sorry about that, `ram` is not maintained anymore but I've kept it in Duck because it doesn't actually take me any time to keep it there. Feel free to use its code compliant with its license. It all fits within [a single file](https://github.com/conradkleinespel/duck/blob/master/projects/ram/src/ram.rs) so re-using it should be as easy as copying/pasting its contents.

**Comment by conradkleinespel** [comment]
Just published `ram` as v8.0 to crates.io if you're still interested in getting it via crates.io.
